# On push to master or update pull request
on:
  push:
    branches:
      - master

name: Build, Test and Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Setup Node.js environment v18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Verify package has version changed
        run: |
          if [ -z "$(git diff --name-only HEAD~1)" ]; then
            echo "No changes detected, exiting..."
            exit 1
          fi
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      # Build
      - name: Build
        run: npm run build
      # Publish to NPM
      - name: Publish to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NODE_AUTH_TOKEN}
          npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}