name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     id-token: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      # Build
      - name: Build
        run: npm run build
      # Publish to NPM
      - run: |
          # Update the package.json file
          npm version "${{ github.ref_name }}" --no-git-tag-version

          # Log the new version to the console
          echo "New version: ${{ github.ref_name }}"
          
          # Publish the new version
          npm publish --provenance -access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      # Send get request to trigger discord bot action
      - name: Send get request to trigger discord bot action
        run: |
          curl -X GET https://team-bot.api.zumito.dev/api/github/release -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"  -H "Content-type: application/json" -d '{"version": "${{ github.ref_name }}", "repository": "${{ github.repository }}", "description": "${{ github.event.release.body }}"}'